configure: accept --with-gaproot

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,41 +1,39 @@
 #!/bin/sh
-# (C) Frank Lübeck 2011
-# configure script for Browse, EDIM and other packages
-# usage: ./configure [GAPPATH]
-# this script creates a "Makefile-myconf" from "Makefile.in" with
-# a link to "Makefile"
+# usage: configure gappath
+# this script creates a `Makefile' from `Makefile.in'
 
-# GAP path
-if [ $# = 0 ]; then
-  GAPPATH="../../"
-else
-  GAPPATH=$1
-fi
-echo "Using $GAPPATH as GAP build directory."
+set -e
 
-if [ ! -e $GAPPATH/sysinfo.gap ]; then
+GAPPATH=../..
+while test "$#" -ge 1 ; do
+  option="$1" ; shift
+  case "$option" in
+    --with-gaproot=*) GAPPATH=${option#--with-gaproot=}; ;;
+    -*)               echo "ERROR: unsupported argument $option" ; exit 1;;
+    *)                GAPPATH="$option" ;;
+  esac
+done
+
+if test ! -r "$GAPPATH/sysinfo.gap" ; then
     echo
     echo "No file $GAPPATH/sysinfo.gap found."
     echo
     echo "Usage: ./configure [GAPPATH]"
     echo "       where GAPPATH is a path to your GAP installation"
-    echo "       and confnam is the name of the GAP configuration to use."
-    echo "       (The default for GAPPATH is \"../..\" and default confignam"
-    echo "       is \"default64\" if it exists, otherwise \"default32\".)"
+    echo "       (The default for GAPPATH is \"../..\")"
     echo
     echo "Either your GAPPATH is incorrect or the GAP it is pointing to"
-    echo "is not properly compiled (do \"./configure ; make\" there first)."
+    echo "is not properly compiled (do \"./configure && make\" there first)."
     echo
-    echo Aborting... No Makefile is generated.
+    echo "Aborting... No Makefile is generated."
     echo
     exit 1
 fi
 
-echo "Using config in $GAPPATH/sysinfo.gap"
-
+echo "Using settings from $GAPPATH/sysinfo.gap"
 rm -f Makefile
-. $GAPPATH/sysinfo.gap
+. "$GAPPATH/sysinfo.gap"
 sed \
-    -e 's|@GAPPATH@|'$GAPPATH'|g' \
-    -e 's/@GAPARCH@/'$GAParch'/g' \
-  Makefile.in > Makefile
+    -e "s;@GAPARCH@;$GAParch;g" \
+    -e "s;@GAPPATH@;$GAPPATH;g" \
+    Makefile.in >Makefile
